# Use the official Golang image as a base
FROM golang:1.19-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy go.mod and go.sum files to leverage Docker cache for dependencies
COPY go.mod go.sum ./

# Install dependencies
RUN go mod download

# Copy the source code into the container
COPY . .

# Build the Go app
RUN go build -o backend .

# Expose the port the Go app will run on
EXPOSE 8080

# Run the Go app
CMD ["./backend"]
