services:
  # Go backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080" # Backend API port
    volumes:
      - ./:/app
    depends_on:
      - postgres
    env_file:
      - .env

  # # Flutter frontend service
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.frontend
  #   volumes:
  #     - ./:/app
  #   ports:
  #     - "8000:8000" # Frontend web port
  #   depends_on:
  #     - backend
  
  # frontend1:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.frontend
  #   volumes:
  #     - ./:/app
  #   ports:
  #     - "8090:8090" # Frontend web port
  #   depends_on:
  #     - backend

  # PostgreSQL database service
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.database
    container_name: chatapp_db
    restart: always 
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  # redis: 
  #   image: redis
  #   ports: 
  #     - "6379:6379"

volumes:
  pg_data:

